### ISSUE TITLE
Connect to local database

### ISSUE THREAD

**Issue by pietz** [qdrant/mcp-server-qdrant#3]
The current variables I saw in the README don't seem to support local qdrant databases specified by a `path` to a local folder.

- Is support for this planned in future updates?
- Is it possible today and I just didn't see it?

**Comment by kacperlukawski** [comment]
@pietz Version 0.5.2 allows the use of the local mode. Please check the current [README](https://github.com/qdrant/mcp-server-qdrant/blob/master/README.md)

**Comment by pietz** [comment]
beautiful, thank you very much!
